title: Rohan Kalia
description: "I'm interested by language model pretraining science, continual learning, infrastructure for AI agents, and writing beautiful software. Also, a movie enthusiast and amateur photographer."
encoding: utf-8
url: "https://rohankalia.dev"
baseurl: ""

# Theme mode setting - "dark" or "light"
theme_mode: light

# Profile image settings
# Uncomment and update these lines to show a profile image
profile_image: /assets/profile_square.jpg
profile_image_alt: "Author profile picture"

# Social links
email: rohantkalia@gmail.com
github_username: rkdune
twitter_username: rohankalia_

exclude: ["README.md", "LICENSE", "*.gem", "*.gemspec", "Gemfile.lock"]