title: Hi, I'm Rohan
description: "Curiosity driven. Movie enthusiast. Trying to get better at photography. Interested in AI interpretability, alignment,  and reinforcement learning."
encoding: utf-8

# Theme mode setting - "dark" or "light"
theme_mode: light

# Profile image settings
# Uncomment and update these lines to show a profile image
profile_image: /assets/profile_square.jpg
profile_image_alt: "Author profile picture"

# Social links
email: rohantkalia [at] gmail [dot] com
github_username: rkdune

exclude: ["README.md", "LICENSE", "*.gem", "*.gemspec", "Gemfile.lock"]